d /etc/skynet-edr 0750 root skynet-edr -
d /etc/skynet-edr/rules.d 0750 root skynet-edr -
d /etc/skynet-edr/agents.d 0750 root skynet-edr -
d /var/lib/skynet-edr 0750 skynet-edr skynet-edr -
d /var/log/skynet-edr 0750 skynet-edr skynet-edr -
d /var/cache/skynet-edr 0750 skynet-edr skynet-edr -
d /run/skynet-edr 0750 skynet-edr skynet-edr -
